import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Modal from "./components/Modal/Modal";
import Toast from "./components/Toast/Toast";
import { ModalProvider } from "./context/modal.context";
import { ToastProvider } from "./context/toast.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Town Name Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
          <ModalProvider>
            {children}
            <Modal />
            <Toast />
          </ModalProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
