import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Modal from "./components/Modal/Modal";
import Toast from "./components/Toast/Toast";
import { ModalProvider } from "./context/modal.context";
import { ToastProvider } from "./context/toast.context";
import { FavoritesProvider } from "./context/favorites.contexts";
import Nav from "./components/Nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Town Name Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </head>
      <body className={inter.className}>
        <ToastProvider>
          <ModalProvider>
            <FavoritesProvider>
              <Nav />
              {children}
              <Modal />
              <Toast />
            </FavoritesProvider>
          </ModalProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
